"""
TLS Handshake Analyzer — Report Generator

Generates Markdown and JSON compliance reports with pass/fail/warning
status per check.
"""

import json
import os
from dataclasses import asdict
from datetime import datetime, timezone
from typing import Optional

from tls_inspector import HandshakeResult
from cert_analyzer import CertAnalysis
from compliance_checker import ComplianceReport, CheckStatus


def generate_markdown_report(
    results: list,
    analyses: list,
    reports: list,
) -> str:
    """Generate a comprehensive Markdown compliance report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "# TLS Compliance Report",
        "",
        f"**Generated:** {now}",
        f"**Hosts Scanned:** {len(results)}",
        "",
    ]

    # Summary table
    lines.extend([
        "## Summary",
        "",
        "| Host | Protocol | Cipher | Key | Expiry | Status |",
        "| ---- | -------- | ------ | --- | ------ | ------ |",
    ])

    status_emoji = {
        CheckStatus.PASS: "PASS",
        CheckStatus.FAIL: "FAIL",
        CheckStatus.WARNING: "WARN",
        CheckStatus.INFO: "INFO",
    }

    for result, analysis, report in zip(results, analyses, reports):
        overall = status_emoji[report.overall_status]
        proto = result.protocol_version or "N/A"
        cipher = result.cipher_suite or "N/A"
        if len(cipher) > 30:
            cipher = cipher[:27] + "..."
        key = f"{analysis.key_type} {analysis.key_size}" if analysis.key_type else "N/A"
        expiry = f"{analysis.days_remaining}d" if not analysis.is_expired else "EXPIRED"
        lines.append(
            f"| {result.host} | {proto} | {cipher} | {key} | {expiry} | {overall} |"
        )

    lines.append("")

    # Detailed results per host
    lines.append("## Detailed Results")
    lines.append("")

    for result, analysis, report in zip(results, analyses, reports):
        lines.extend([
            f"### {result.host}:{result.port}",
            "",
            f"**Overall Status:** {status_emoji[report.overall_status]}",
            f"**Protocol:** {result.protocol_version}",
            f"**Cipher Suite:** {result.cipher_suite}",
            f"**Cipher Bits:** {result.cipher_bits}",
            "",
        ])

        # Certificate details
        if analysis.subject_cn:
            lines.extend([
                "**Certificate Details:**",
                "",
                f"- Subject CN: `{analysis.subject_cn}`",
                f"- Issuer: {analysis.issuer_org} ({analysis.issuer_cn})",
                f"- Valid: {analysis.valid_from} to {analysis.valid_until}",
                f"- Days Remaining: {analysis.days_remaining}",
                f"- Key: {analysis.key_type} {analysis.key_size}-bit",
                f"- SANs: {analysis.san_count}",
                "",
            ])

        # Compliance checks table
        lines.extend([
            "**Compliance Checks:**",
            "",
            "| Check | Status | Detail |",
            "| ----- | ------ | ------ |",
        ])

        for check in report.checks:
            status = status_emoji[check.status]
            detail = check.detail.replace("|", "\\|")
            lines.append(f"| {check.check_name} | {status} | {detail} |")

        lines.append("")

        # Warnings
        if analysis.warnings:
            lines.append("**Warnings:**")
            lines.append("")
            for w in analysis.warnings:
                lines.append(f"- {w}")
            lines.append("")

        if result.error:
            lines.append(f"**Connection Note:** {result.error}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # Footer
    lines.extend([
        "",
        "*Report generated by TLS Handshake Analyzer — "
        "AI Sentinel Cybersecurity Suite*",
    ])

    return "\n".join(lines)


def generate_json_report(
    results: list,
    analyses: list,
    reports: list,
) -> dict:
    """Generate a JSON compliance report."""
    now = datetime.now(timezone.utc).isoformat()

    json_report = {
        "report_type": "tls_compliance",
        "generated_at": now,
        "hosts_scanned": len(results),
        "results": [],
    }

    for result, analysis, report in zip(results, analyses, reports):
        host_entry = {
            "host": result.host,
            "port": result.port,
            "protocol_version": result.protocol_version,
            "cipher_suite": result.cipher_suite,
            "cipher_bits": result.cipher_bits,
            "overall_status": report.overall_status.value,
            "pass_count": report.pass_count,
            "fail_count": report.fail_count,
            "warning_count": report.warning_count,
            "certificate": {
                "subject_cn": analysis.subject_cn,
                "issuer_cn": analysis.issuer_cn,
                "issuer_org": analysis.issuer_org,
                "valid_from": analysis.valid_from,
                "valid_until": analysis.valid_until,
                "days_remaining": analysis.days_remaining,
                "is_expired": analysis.is_expired,
                "is_self_signed": analysis.is_self_signed,
                "key_type": analysis.key_type,
                "key_size": analysis.key_size,
                "san_count": analysis.san_count,
                "hostname_match": analysis.hostname_match,
            },
            "checks": [
                {
                    "category": c.category,
                    "name": c.check_name,
                    "status": c.status.value,
                    "actual": c.actual_value,
                    "expected": c.expected,
                    "detail": c.detail,
                }
                for c in report.checks
            ],
            "warnings": analysis.warnings,
            "connection_error": result.error,
        }
        json_report["results"].append(host_entry)

    return json_report


def save_reports(
    results: list,
    analyses: list,
    reports: list,
    output_dir: str = "reports",
    formats: str = "both",
) -> list:
    """
    Save reports to files.

    Returns list of saved file paths.
    """
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    saved = []

    if formats in ("markdown", "both"):
        md_content = generate_markdown_report(results, analyses, reports)
        md_path = os.path.join(output_dir, f"tls_report_{timestamp}.md")
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)
        saved.append(md_path)

    if formats in ("json", "both"):
        json_content = generate_json_report(results, analyses, reports)
        json_path = os.path.join(output_dir, f"tls_report_{timestamp}.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(json_content, f, indent=2, default=str)
        saved.append(json_path)

    return saved
