<script setup>
import StatusBadge from '../shared/StatusBadge.vue'

defineProps({ doc: Object })
defineEmits(['close'])
</script>

<template>
  <div class="card">
    <div class="flex items-start justify-between mb-4">
      <div>
        <h3 class="text-lg font-semibold text-gray-800">{{ doc.title }}</h3>
        <div class="flex items-center gap-2 mt-1">
          <StatusBadge :status="doc.status" />
          <span class="text-xs text-gray-500">v{{ doc.version }}</span>
          <span v-if="doc.llm_model_used" class="text-xs text-gray-400">Generated by {{ doc.llm_model_used }}</span>
        </div>
      </div>
      <button @click="$emit('close')" class="text-gray-400 hover:text-gray-600 text-xl">&times;</button>
    </div>
    <div class="prose prose-sm max-w-none whitespace-pre-wrap bg-gray-50 p-5 rounded-lg max-h-[600px] overflow-y-auto">{{ doc.content }}</div>
  </div>
</template>
